// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.reservetickets.domain;

import com.springsource.roo.reservetickets.domain.Auditorium;
import com.springsource.roo.reservetickets.domain.AuditoriumDataOnDemand;
import com.springsource.roo.reservetickets.domain.AuditoriumIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AuditoriumIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AuditoriumIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AuditoriumIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AuditoriumIntegrationTest: @Transactional;
    
    @Autowired
    AuditoriumDataOnDemand AuditoriumIntegrationTest.dod;
    
    @Test
    public void AuditoriumIntegrationTest.testCountAuditoriums() {
        Assert.assertNotNull("Data on demand for 'Auditorium' failed to initialize correctly", dod.getRandomAuditorium());
        long count = Auditorium.countAuditoriums();
        Assert.assertTrue("Counter for 'Auditorium' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AuditoriumIntegrationTest.testFindAuditorium() {
        Auditorium obj = dod.getRandomAuditorium();
        Assert.assertNotNull("Data on demand for 'Auditorium' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Auditorium' failed to provide an identifier", id);
        obj = Auditorium.findAuditorium(id);
        Assert.assertNotNull("Find method for 'Auditorium' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Auditorium' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AuditoriumIntegrationTest.testFindAllAuditoriums() {
        Assert.assertNotNull("Data on demand for 'Auditorium' failed to initialize correctly", dod.getRandomAuditorium());
        long count = Auditorium.countAuditoriums();
        Assert.assertTrue("Too expensive to perform a find all test for 'Auditorium', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Auditorium> result = Auditorium.findAllAuditoriums();
        Assert.assertNotNull("Find all method for 'Auditorium' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Auditorium' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AuditoriumIntegrationTest.testFindAuditoriumEntries() {
        Assert.assertNotNull("Data on demand for 'Auditorium' failed to initialize correctly", dod.getRandomAuditorium());
        long count = Auditorium.countAuditoriums();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Auditorium> result = Auditorium.findAuditoriumEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Auditorium' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Auditorium' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AuditoriumIntegrationTest.testFlush() {
        Auditorium obj = dod.getRandomAuditorium();
        Assert.assertNotNull("Data on demand for 'Auditorium' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Auditorium' failed to provide an identifier", id);
        obj = Auditorium.findAuditorium(id);
        Assert.assertNotNull("Find method for 'Auditorium' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAuditorium(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Auditorium' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AuditoriumIntegrationTest.testMergeUpdate() {
        Auditorium obj = dod.getRandomAuditorium();
        Assert.assertNotNull("Data on demand for 'Auditorium' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Auditorium' failed to provide an identifier", id);
        obj = Auditorium.findAuditorium(id);
        boolean modified =  dod.modifyAuditorium(obj);
        Integer currentVersion = obj.getVersion();
        Auditorium merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Auditorium' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AuditoriumIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Auditorium' failed to initialize correctly", dod.getRandomAuditorium());
        Auditorium obj = dod.getNewTransientAuditorium(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Auditorium' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Auditorium' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Auditorium' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AuditoriumIntegrationTest.testRemove() {
        Auditorium obj = dod.getRandomAuditorium();
        Assert.assertNotNull("Data on demand for 'Auditorium' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Auditorium' failed to provide an identifier", id);
        obj = Auditorium.findAuditorium(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Auditorium' with identifier '" + id + "'", Auditorium.findAuditorium(id));
    }
    
}
