// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.reservetickets.domain;

import com.springsource.roo.reservetickets.domain.Auditorium;
import com.springsource.roo.reservetickets.domain.AuditoriumDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect AuditoriumDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AuditoriumDataOnDemand: @Component;
    
    private Random AuditoriumDataOnDemand.rnd = new SecureRandom();
    
    private List<Auditorium> AuditoriumDataOnDemand.data;
    
    public Auditorium AuditoriumDataOnDemand.getNewTransientAuditorium(int index) {
        Auditorium obj = new Auditorium();
        setNumberOfAuditorium(obj, index);
        setNumberOfPlaces(obj, index);
        setNumberOfRows(obj, index);
        return obj;
    }
    
    public void AuditoriumDataOnDemand.setNumberOfAuditorium(Auditorium obj, int index) {
        int numberOfAuditorium = index;
        obj.setNumberOfAuditorium(numberOfAuditorium);
    }
    
    public void AuditoriumDataOnDemand.setNumberOfPlaces(Auditorium obj, int index) {
        int numberOfPlaces = index;
        obj.setNumberOfPlaces(numberOfPlaces);
    }
    
    public void AuditoriumDataOnDemand.setNumberOfRows(Auditorium obj, int index) {
        int numberOfRows = index;
        obj.setNumberOfRows(numberOfRows);
    }
    
    public Auditorium AuditoriumDataOnDemand.getSpecificAuditorium(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Auditorium obj = data.get(index);
        Long id = obj.getId();
        return Auditorium.findAuditorium(id);
    }
    
    public Auditorium AuditoriumDataOnDemand.getRandomAuditorium() {
        init();
        Auditorium obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Auditorium.findAuditorium(id);
    }
    
    public boolean AuditoriumDataOnDemand.modifyAuditorium(Auditorium obj) {
        return false;
    }
    
    public void AuditoriumDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Auditorium.findAuditoriumEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Auditorium' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Auditorium>();
        for (int i = 0; i < 10; i++) {
            Auditorium obj = getNewTransientAuditorium(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
