// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.reservetickets.domain;

import com.springsource.roo.reservetickets.domain.Price;
import com.springsource.roo.reservetickets.domain.PriceDataOnDemand;
import com.springsource.roo.reservetickets.domain.PriceIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PriceIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PriceIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PriceIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PriceIntegrationTest: @Transactional;
    
    @Autowired
    PriceDataOnDemand PriceIntegrationTest.dod;
    
    @Test
    public void PriceIntegrationTest.testCountPrices() {
        Assert.assertNotNull("Data on demand for 'Price' failed to initialize correctly", dod.getRandomPrice());
        long count = Price.countPrices();
        Assert.assertTrue("Counter for 'Price' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PriceIntegrationTest.testFindPrice() {
        Price obj = dod.getRandomPrice();
        Assert.assertNotNull("Data on demand for 'Price' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Price' failed to provide an identifier", id);
        obj = Price.findPrice(id);
        Assert.assertNotNull("Find method for 'Price' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Price' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PriceIntegrationTest.testFindAllPrices() {
        Assert.assertNotNull("Data on demand for 'Price' failed to initialize correctly", dod.getRandomPrice());
        long count = Price.countPrices();
        Assert.assertTrue("Too expensive to perform a find all test for 'Price', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Price> result = Price.findAllPrices();
        Assert.assertNotNull("Find all method for 'Price' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Price' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PriceIntegrationTest.testFindPriceEntries() {
        Assert.assertNotNull("Data on demand for 'Price' failed to initialize correctly", dod.getRandomPrice());
        long count = Price.countPrices();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Price> result = Price.findPriceEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Price' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Price' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PriceIntegrationTest.testFlush() {
        Price obj = dod.getRandomPrice();
        Assert.assertNotNull("Data on demand for 'Price' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Price' failed to provide an identifier", id);
        obj = Price.findPrice(id);
        Assert.assertNotNull("Find method for 'Price' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPrice(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Price' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PriceIntegrationTest.testMergeUpdate() {
        Price obj = dod.getRandomPrice();
        Assert.assertNotNull("Data on demand for 'Price' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Price' failed to provide an identifier", id);
        obj = Price.findPrice(id);
        boolean modified =  dod.modifyPrice(obj);
        Integer currentVersion = obj.getVersion();
        Price merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Price' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PriceIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Price' failed to initialize correctly", dod.getRandomPrice());
        Price obj = dod.getNewTransientPrice(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Price' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Price' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Price' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PriceIntegrationTest.testRemove() {
        Price obj = dod.getRandomPrice();
        Assert.assertNotNull("Data on demand for 'Price' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Price' failed to provide an identifier", id);
        obj = Price.findPrice(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Price' with identifier '" + id + "'", Price.findPrice(id));
    }
    
}
