// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.reservetickets.domain;

import com.springsource.roo.reservetickets.domain.FilmType;
import com.springsource.roo.reservetickets.domain.Price;
import com.springsource.roo.reservetickets.domain.PriceDataOnDemand;
import com.springsource.roo.reservetickets.domain.PriceType;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect PriceDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PriceDataOnDemand: @Component;
    
    private Random PriceDataOnDemand.rnd = new SecureRandom();
    
    private List<Price> PriceDataOnDemand.data;
    
    public Price PriceDataOnDemand.getNewTransientPrice(int index) {
        Price obj = new Price();
        setFilmType(obj, index);
        setPriceType(obj, index);
        setValueOfPrice(obj, index);
        return obj;
    }
    
    public void PriceDataOnDemand.setFilmType(Price obj, int index) {
        FilmType filmType = FilmType.class.getEnumConstants()[0];
        obj.setFilmType(filmType);
    }
    
    public void PriceDataOnDemand.setPriceType(Price obj, int index) {
        PriceType priceType = PriceType.class.getEnumConstants()[0];
        obj.setPriceType(priceType);
    }
    
    public void PriceDataOnDemand.setValueOfPrice(Price obj, int index) {
        int valueOfPrice = index;
        obj.setValueOfPrice(valueOfPrice);
    }
    
    public Price PriceDataOnDemand.getSpecificPrice(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Price obj = data.get(index);
        Long id = obj.getId();
        return Price.findPrice(id);
    }
    
    public Price PriceDataOnDemand.getRandomPrice() {
        init();
        Price obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Price.findPrice(id);
    }
    
    public boolean PriceDataOnDemand.modifyPrice(Price obj) {
        return false;
    }
    
    public void PriceDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Price.findPriceEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Price' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Price>();
        for (int i = 0; i < 10; i++) {
            Price obj = getNewTransientPrice(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
