// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.reservetickets.domain;

import com.springsource.roo.reservetickets.domain.AuditoriumDataOnDemand;
import com.springsource.roo.reservetickets.domain.FilmDataOnDemand;
import com.springsource.roo.reservetickets.domain.Show;
import com.springsource.roo.reservetickets.domain.ShowDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ShowDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ShowDataOnDemand: @Component;
    
    private Random ShowDataOnDemand.rnd = new SecureRandom();
    
    private List<Show> ShowDataOnDemand.data;
    
    @Autowired
    AuditoriumDataOnDemand ShowDataOnDemand.auditoriumDataOnDemand;
    
    @Autowired
    FilmDataOnDemand ShowDataOnDemand.filmDataOnDemand;
    
    public Show ShowDataOnDemand.getNewTransientShow(int index) {
        Show obj = new Show();
        setDateOfShow(obj, index);
        return obj;
    }
    
    public void ShowDataOnDemand.setDateOfShow(Show obj, int index) {
        Date dateOfShow = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateOfShow(dateOfShow);
    }
    
    public Show ShowDataOnDemand.getSpecificShow(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Show obj = data.get(index);
        Long id = obj.getId();
        return Show.findShow(id);
    }
    
    public Show ShowDataOnDemand.getRandomShow() {
        init();
        Show obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Show.findShow(id);
    }
    
    public boolean ShowDataOnDemand.modifyShow(Show obj) {
        return false;
    }
    
    public void ShowDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Show.findShowEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Show' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Show>();
        for (int i = 0; i < 10; i++) {
            Show obj = getNewTransientShow(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
