// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.reservetickets.domain;

import com.springsource.roo.reservetickets.domain.Price;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Price_Roo_Configurable {
    
    declare @type: Price: @Configurable;
    
}
